[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_build.filesystem = littlefs

lib_ldf_mode = deep+

lib_deps =
    crankyoldgit/IRremoteESP8266
    bblanchon/ArduinoJson